python_cms/blueprints/auth.py
from flask import Blueprint, redirect, request, url_for
from flask_login import login_user, login_required, logout_user
import json
import requests
from oauthlib.oauth2 import WebApplicationClient
from os import environ
from python_cms.models.user import UserModel

# Oauth Configuration
GOOGLE_CLIENT_ID = environ.get("GOOGLE_CLIENT_ID", None)
GOOGLE_CLIENT_SECRET = environ.get("GOOGLE_CLIENT_SECRET", None)
GOOGLE_DISCOVERY_URL = (
    "https://accounts.google.com/.well-known/openid-configuration")

# OAuth2 client setup
client = WebApplicationClient(GOOGLE_CLIENT_ID)

auth_blueprint = Blueprint("auth", __name__)


@auth_blueprint.route("/login")
def login():
  # Find out what URL to hit for Google login
  google_provider_cfg = requests.get(GOOGLE_DISCOVERY_URL).json()
  authorization_endpoint = google_provider_cfg["authorization_endpoint"]

  # construct the request for Google login and provide
  # scopes that let you retrieve user's profile from Google
  request_uri = client.prepare_request_uri(
      authorization_endpoint,
      redirect_uri=request.host_url + "authorize",
      scope=["openid", "email", "profile"],
  )
  return redirect(request_uri)


@auth_blueprint.route("/authorize")
def authorize():
  # Get authorization code Google sent back to you
  code = request.args.get("code")

  # Find out what URL to hit to get tokens that allow you to ask for
  # things on behalf of a user
  google_provider_cfg = requests.get(GOOGLE_DISCOVERY_URL).json()
  token_endpoint = google_provider_cfg["token_endpoint"]

  # Prepare and send request to get tokens!
  token_url, headers, body = client.prepare_token_request(
      token_endpoint,
      authorization_response=request.url,
      redirect_url=request.base_url,
      code=code,
  )
  # send the request to get the tokens
  token_response = requests.post(
      token_url,
      headers=headers,
      data=body,
      auth=(GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET),
  )

  # Parse the tokens from the response body
  client.parse_request_body_response(json.dumps(token_response.json()))

  # Now that we have tokens let's find and hit the URL
  # from Google that gives the user's profile information,
  # including their Google Profile Image and Email
  userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
  uri, headers, body = client.add_token(userinfo_endpoint)
  userinfo_response = requests.get(uri, headers=headers, data=body)

  # We want to make sure their email is verified.
  # The user authenticated with Google, authorized our
  # app, and now we've verified their email through Google!
  print(userinfo_response.json())
  if userinfo_response.json().get("email_verified"):
    unique_id = userinfo_response.json()["sub"]
    users_email = userinfo_response.json()["email"]
    picture = userinfo_response.json()["picture"]
    users_name = f'{userinfo_response.json()["family_name"]} {userinfo_response.json()["given_name"]}'
  else:
    return "User email not available or not verified by Google.", 400

  # Create a user in our database with the information provided
  # by Google
  user = UserModel(id=unique_id,
                   name=users_name,
                   email=users_email,
                   picture=picture)

  # Doesn't exist? Add to database
  if not UserModel.get(unique_id):
    user.save()

  # Begin the user session by logging the user in.
  # user should be an instance of your `User` class
  login_user(user)

  # redirect the user back to homepage
  return redirect(url_for("pages.index"))


@auth_blueprint.route("/logout")
@login_required
def logout():
  logout_user()
  return redirect(url_for("pages.index"))

python_cms/blueprints/pages.py
from fileinput import filename
from posixpath import split
from flask import Blueprint, render_template, request, url_for, send_from_directory
from flask.helpers import flash
from flask_login import login_required, current_user
from python_cms.models.user import UserModel
from werkzeug.utils import secure_filename, redirect
import os
from python_cms.models.post import PostModel
from python_cms.forms.post_form import PostForm
from python_cms.forms.contact_form import ContactForm
from python_cms.models.category import CategoryModel
from python_cms.models.author import AuthorModel
from python_cms.models.tag import TagModel
from python_cms.models.post_tag import PostTagLink
import python_cms
import html
from flask_ckeditor import upload_success, upload_fail
from datetime import datetime
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from python_cms.db import BaseModel, db
from dateutil import parser

import bleach  # https://bleach.readthedocs.io/en/latest/

pages_blueprint = Blueprint("pages", __name__)

now = datetime.now()


def get_post_author(posts, id):
  for post in posts:
    if post.author_id == id:
      name = post.author.name
      return name


@pages_blueprint.route("/")
def index():
  posts = PostModel.get_all()
  return render_template('index.html.j2', posts=posts)


@pages_blueprint.route("/posts/<string:category_name>")
def category(category_name):
  posts = PostModel.get_all()

  return render_template('category.html.j2',
                         posts=posts,
                         category=category_name)


@pages_blueprint.route("/posts/tag/<string:tag_id>")
def tag(tag_id):
  tag_posts = PostTagLink.get_by_tag_id(tag_id)
  posts = []
  for tag_post in tag_posts:
    posts.append(PostModel.get(tag_post.post_id))

  return render_template('tag_posts.html.j2',
                         posts=posts,
                         tag_name=tag_posts[0].tag_name)


@pages_blueprint.route('/mission')
def mission():
  return render_template('mission.html.j2')


@pages_blueprint.route('/about_authors')
def about_authors():
  auths = AuthorModel.get_all()
  for auth in auths:
    print(auth.name)
  return render_template('about_authors.html.j2', auths=auths)


@pages_blueprint.route('/connect_us')
def connect_us():
  return render_template('/connect_us.html.j2')


@pages_blueprint.route('/connection', methods=['GET', 'POST'])
def connection():
  form = ContactForm()
  if request.method == 'POST' and form.validate_on_submit():
    # https://www.tutorialspoint.com/send-mail-from-your-gmail-account-using-python
    email = request.form.get("email")
    mail_content = request.form.get("message")
    subject = request.form.get("subject")
    mail_content = mail_content + "(" + email + ")"

    sender_address = 'solamateria@gmail.com'
    sender_pass = 'EgyedulAzAnyag'
    receiver_address = 'csampaie.5@gmail.com'

    message = MIMEMultipart()
    message['From'] = sender_address
    message['To'] = receiver_address
    message['Subject'] = subject

    #The body and the attachments for the mail
    message.attach(MIMEText(mail_content, 'plain'))

    #Create SMTP session for sending the mail
    session = smtplib.SMTP('smtp.gmail.com', 587)  #use gmail with port
    session.starttls()  #enable security
    session.login(sender_address,
                  sender_pass)  #login with mail_id and password
    text = message.as_string()
    session.sendmail(sender_address, receiver_address, text)
    session.quit()

    return redirect(url_for('pages.connection'))

  return render_template('/connection.html.j2', form=form)


def subscribe():
  form = ContactForm()
  if request.method == 'POST' and form.validate_on_submit():
    email = request.form.get("email")
    mail_content = email
    subject = "Feliratkozás"

    sender_address = 'solamateria@gmail.com'
    sender_pass = 'EgyedulAzAnyag'
    receiver_address = 'csampaie.5@gmail.com'

    message = MIMEMultipart()
    message['From'] = sender_address
    message['To'] = receiver_address
    message['Subject'] = subject

    #The body and the attachments for the mail
    message.attach(MIMEText(mail_content, 'plain'))

    #Create SMTP session for sending the mail
    session = smtplib.SMTP('smtp.gmail.com', 587)  #use gmail with port
    session.starttls()  #enable security
    session.login(sender_address,
                  sender_pass)  #login with mail_id and password
    text = message.as_string()
    session.sendmail(sender_address, receiver_address, text)
    session.quit()


@pages_blueprint.route('/author/<string:id>')
def auth_post(id):
  posts = PostModel.get_all()
  name = get_post_author(posts, id)
  return render_template('author_post.html.j2', posts=posts, id=id, name=name)


@pages_blueprint.route("/add", methods=['GET', 'POST'])
@login_required
def create_post():
  form = PostForm()
  all_tags = TagModel.get_all()

  form.category.choices = [(1, 'Filozófia'), (2, 'Tudomány'), (3, 'Politika'),
                           (4, 'Versus')]
  if request.method == 'POST' and form.validate_on_submit():

    tags_from_form = request.form.get('added_tags')
    tags = list(set(tags_from_form.split("-")[1:]))
    # tags = list(set(tags_from_form.split("-")))[1:]

    # print(tags)
    unescaped_body = html.unescape(request.form.get('body'))
    clean_body = bleach.clean(unescaped_body,
                              tags=bleach.sanitizer.ALLOWED_TAGS +
                              ['div', 'br', 'p', 'h1', 'h2', 'img', 'h3'],
                              attributes=['src', 'alt', 'style'])
    title = request.form.get('title')

    body = clean_body
    file = request.files['teaser_image']
    if not file:
      flash('Kép nélkül nem tud postot létrehozni!', 'error')
      return render_template('create_post.html.j2', form=form, tags=all_tags)
    if not tags:
      flash('Adjon meg cimkét!', 'error')
      return render_template('create_post.html.j2', form=form, tags=all_tags)

    filename = secure_filename(file.filename)
    print(filename)
    file.save(os.path.join(python_cms.ROOT_PATH, 'files_upload', filename))
    promoted = request.form.get('promoted')
    category_id = request.form.get('category')
    category = CategoryModel.get(category_id)
    # current date and time
    date_time = now.strftime("%d/%m/%Y")
    # date_time = parser.parse(now.strftime("%c"))

    # print("-----------------", category.name)
    post = PostModel(title, body, current_user.get_id(), filename,
                     bool(promoted), category_id, category.name, date_time)

    post.save()

    print()

    # posts = PostModel.get_all()
    # print(posts[len(posts) - 1].id)
    for tag in tags:
      # print(tag)
      tag_m = TagModel.get_by_name(tag)
      save_tag = PostTagLink(post.id, tag_m.id, tag)
      save_tag.save()

    flash(f'Post with title: {title} is created')
    return redirect(url_for('pages.create_post'))

  return render_template('create_post.html.j2', form=form, tags=all_tags)


@pages_blueprint.route('/files/<path:filename>')
def uploaded_files(filename):
  path = os.path.join(python_cms.ROOT_PATH, 'files_upload')
  return send_from_directory(path, filename)


@pages_blueprint.route("/post/<string:post_id>")
def single_post(post_id):
  post = PostModel.get(post_id)
  tags = PostTagLink.get_by_post_id(post_id)
  return render_template('post.html.j2', post=post, tags=tags)


@pages_blueprint.route('/upload', methods=['POST'])
def upload():
  f = request.files.get('upload')
  # Add more validations here
  extension = f.filename.split('.')[-1].lower()
  if extension not in ['jpg', 'gif', 'png', 'jpeg']:
    return upload_fail(message='Image only!')
  file_name = os.path.join(python_cms.ROOT_PATH, 'files_upload', f.filename)
  f.save(os.path.join(file_name))
  url = url_for('pages.uploaded_files', filename=f.filename)
  return upload_success(url=url)  # return upload_success call


@pages_blueprint.route('/post/delete/<string:post_id>')
@login_required
def delete_post(post_id):
  post = PostModel.get(post_id)
  if post.author_id != current_user.get_id():
    return "Csak bejelentkezett felhasználok törölhetnek postokat!", 403

  post_tags = PostTagLink.get_by_post_id(post_id)
  for post_tag in post_tags:
    post_tag.delete()

  post.delete()
  flash(f'A {post.title} című post törölve lett!')
  return redirect(url_for('pages.index'))


@pages_blueprint.route('/post/edit/<string:post_id>', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
  post = PostModel.get(post_id)
  tags = PostTagLink.get_by_post_id(post_id)
  all_tags = TagModel.get_all()

  if post.author_id != current_user.get_id():
    return "Csak bejelentkezett felhasználók szerkeszthetik a posztot", 403

  form = PostForm()
  form.category.choices = [(1, 'Filozófia'), (2, 'Tudomány'), (3, 'Politika'),
                           (4, 'Versus')]

  if request.method == 'POST' and form.validate_on_submit():
    unescaped_body = html.unescape(request.form.get('body'))
    clean_body = bleach.clean(unescaped_body,
                              tags=bleach.sanitizer.ALLOWED_TAGS +
                              ['div', 'br', 'p', 'h1', 'h2', 'img', 'h3'],
                              attributes=['src', 'alt', 'style'])

    body = clean_body
    title = request.form.get('title')
    filename = request.form.get('original_teaser_image')

    if not filename:
      file = request.files['teaser_image']
      filename = secure_filename(file.filename)

    if not filename:

      flash('Kép nélkül nem tud postot létrehozni!', 'error')
      filename = post.teaser_image

      print("-------------------------", post.teaser_image)
      # return redirect(url_for('pages.edit_post'))
      return render_template('edit_post.html.j2',
                             form=form,
                             tags=all_tags,
                             post=post,
                             post_id=post_id)

    post.teaser_image = filename

python_cms/templates/about_authors.html.j2
{% extends 'base.html.j2' %}
{% block title %} Sszerzőkről {% endblock %}

{%block headsource %}  
{# <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> #}
{# <link rel="stylesheet" href="{{ url_for('static', filename='author.css') }}" /> #}
{% endblock %}

{% block content %}
    <h3>Szerzőinkról</h3>

    <div class="authors">
        {% for auth in auths %}
            <div class="author">
                <a href="#">
                    {# <img src="{{url_for('static', filename='marx_2.jpg')}}" alt="szerző" width="500" height="600"> #}
                    {# <img src="/static/{{auth.profile_pic}}" alt="szerző" width="500" height="600"> #}

                </a>
                 <ul>
                    <li>{{auth.name}}</li>
                    <li>{{auth.vegzettseg}}</li>
                    <li>{{auth.tema}}</li>
                    <li>{{auth.bemutatkozas}}</li>
                </ul>
        {% endfor %}


                    <div class="author-data">
                        <ul>
                            <li>Név</li>
                            <li>Végzettség</li>
                            <li>Kedvenc téma</li>
                            <li>Rövid bemutatkozás</li>
                        </ul>
                    </div>
        </div>
    </div>

{% endblock %}

python_cms/templates/author_post.html.j2
{% extends 'base.html.j2' %}
{% block title %} Szezői postok {% endblock %}
{%block headsource %}  
{# <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> #}
<link rel="stylesheet" href="{{ url_for('static', filename='style_index.css') }}" />
{% endblock %}

{% block content %}
  {% if posts|length == 0 %}
  <h1 class="no-posts">Nincsenek bejegyzések</h1>
  {% endif %}

  {% for message in get_flashed_messages()  %}
   <div class="toast toast-success">
       <button class="btn btn-clear float-right"></button>
         {{message}}
   </div>
  {% endfor %}



    {% if posts %}
    <h3>{{name}} postjai</h3>
    
     
    
    {% endif %}
{#  #}
<section class="posts">
  {% for post in posts|sort(attribute="id", reverse=true)|selectattr("author_id", "equalto", id) %}
    <article class="post">
        <div class="post-data">
            <div class="img-div">
            <a href="/post/{{ post.id }}">
              <img src="/files/{{post.teaser_image}}" alt="">
            </a>
                
            </div>
            <div class="other-data">
                <div class="catauth">
                    <div class="post-category"><a href="/posts/{{ post.category_name }}">{{ post.category_name }}</a></div>      
                    <div class="post-auther"><a href="/author/{{ post.author_id}}">{{post.author.name}} - {{post.create_date}}</a></div>
                </div>
                <div class="title">
                    <a href="/post/{{ post.id }}">{{post.title}}"</a>
                </div>
            </div>
        </article>
    </div>
  {% endfor %}
</section>
{% endblock %}

{# {% block bodysource %} <script src="{{url_for('static', filename="pic-flex.js")}}"></script>  #}
{# {% endblock %} #}

python_cms/templates/base.html.j2
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="filozófia, materializmus, fizikalizmus, marx, engels, anyag, anyagiság">  
    <meta name="description" content="ide az oldal rövid leírása jön">  
    <title>{% block title %} {% endblock %}</title>
    {# <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css" /> #}
    {# <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css" /> #}
    {# <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css" /> #}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous" />
    {# <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@0;1&display=swap" rel="stylesheet"> #}
    {# <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> #}
    <link href="https://fonts.googleapis.com/css2?family=Oxanium:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet">

     <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />


    {# <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> #}
    

    {% block headsource %} {% endblock %}
</head>

<body>
    <header>
        <div class="header-nav">
            <div class="logo">
                <a href="{{ url_for('pages.index') }}">
                    <h1>Sola Materia</h1>
                    <h2>Egyedül az Anyag</h2>
                </a>
            </div>
            <!-- nav.menu-container>ul.menu>(li.menu-item>a[href="#"])*5 -->
            <div class="kategoria-div" id="kategoria">
                    {% if current_user.is_authenticated %}
                        <li class="kategoria">Bejelentkezve: {{current_user.name}}</li>
                    {% else %}
                    <li class="kategoria">MENÜ</li>
                    {% endif %}
            </div>
            <nav class="menu-container">
                <ul class="menu">
                    
                        <li class="menu-item main-menu-item"><a href="/posts/Filozófia">Filozófia</a></li>
                        <li class="menu-item main-menu-item"><a href="/posts/Tudomány">Tudomány</a></li>
                        <li class="menu-item main-menu-item"><a href="/posts/Politika">Politika</a></li>
                        <li class="menu-item main-menu-item"><a href="/posts/Versus">Versus</a></li>

                   {% if current_user.is_authenticated %}
                        {% block menucontent%} {% endblock %}
                        <li class="menu-item menu-create-post"><a href="{{ url_for('pages.create_post') }}">Create Post</a></li>
                        <li class="menu-item menu-log-out"><a href="{{ url_for('auth.logout') }}">Log out</a></li>
                        <div></div>
                    {% else %}
                        <li class="menu-item menu-log-in"><a href="{{ url_for('auth.login') }}">Log in</a></li>
                    {% endif %}
                </ul>

                {% block navcontent %} {% endblock %}

            </nav>

        </div>
        <div class="log-in">
            {% if current_user.is_authenticated %}
                <div class="chip loged-in">
                    <div class="user-data">
                        <img class="user-pic" src="{{ current_user.profile_pic }}" alt="">
                        <div class="current-user">{{ current_user.name }}</div>
                    </div>
                    <div class="loged-in-submenu">
                        <a class="create-post" href="{{ url_for('pages.create_post') }}">Create Post</a>
                        <a class="log-out" href="{{ url_for('auth.logout') }}">Log out</a>
                    </div>
                </div>
            {% else %}
                <a href="{{ url_for('auth.login') }}">Log in</a>
            {% endif %}
        </div>
    </header>

    <main class="clearfix">
      {% block content %} {% endblock %}
        {# <div class="center">
    <div class="pagination">
      <!-- &laquo; -->
      <a href="#" class="page-num" id="prev">&laquo; Előző
        <!-- <ion-icon name="play-outline"></ion-icon> -->
      </a>
      <a href="#" class="page-num">1</a>
      <a href="#" class="active page-num">2</a>
      <a href="#" class="page-num">3</a>
      <a href="#" class="page-num">4</a>
      <a href="#" class="page-num">5</a>
      <a href="#" class="page-num">6</a>
      <a href="#" class="page-num" id="next">Következő &raquo;</a>
    </div>
  </div> #}

    </main>

    <footer>
    {# <div class="rolunk-fel"> #}
        <div class="rolunk">
            <span>Rólunk</span>
            <a href="{{ url_for('pages.mission') }}">Küldetésünk</a>
            <a href="{{ url_for('pages.about_authors') }}">A szerzőkről</a>
            {# <a href="{{ url_for('pages.connect_us') }}">Csatlakozz</a> #}
            <a href="{{ url_for('pages.connection') }}">Kapcsolat</a>
        </div>

        <div class="feliratkozas">
            <h2>Iratkozz fel</h2>
            <form class="email-bar" action="/subscribe" method="POST">
                <input type="email" name="feliratkozas" class="email-field" placeholder="Email címed">
                <a href="#"><i class="fas fa-paper-plane email-button"></i></a>
            </form>

        </div>
    {# </div> #}
        
    <div class="logo">
        <a href="{{ url_for('pages.index') }}">
            <h1>Sola Materia</h1>
            <h2>Egyedül az Anyag</h2>
        </a>

    </div>

    </footer>

    <script src="../static/menu.js"></script>
{% block bodysource %} {% endblock %}
</body>

</html>

python_cms/templates/category.html.j2
{% extends 'base.html.j2' %}
{% block title %} {{category}} {% endblock %}

{%block headsource %}  
{# <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> #}
<link rel="stylesheet" href="{{ url_for('static', filename='style_index.css') }}" /> 
{% endblock %}

{% block content %}
{# fl #}

  {% for message in get_flashed_messages()  %}
   <div class="toast toast-success">
       <button class="btn btn-clear float-right"></button>
         {{message}}
   </div>
  {% endfor %}

{# {% if posts %} #}
  <h3>{{category}}</h3>
{# {% else %} 
  <h1 class="no-posts">Nincsenek bejegyzések</h1> 
{% endif %} #}

<section class="posts">
  {% for post in posts|sort(attribute="id", reverse=true)|selectattr("category_name", "equalto", category) %}

    <article class="post">
        <div class="post-data">
            <div class="img-div">
            <a href="/post/{{ post.id }}">
              <img src="/files/{{post.teaser_image}}" alt="">
            </a>
                
            </div>
            <div class="other-data">
                <div class="catauth">
                    <div class="post-category"><a href="#" >{{ post.category_name }}</a></div>
                    <div class="post-auther"><a href="/author/{{ post.author_id}}">{{post.author.name}} - {{post.create_date}}</a></div>
                </div>
                <div class="title">
                    <a href="/post/{{ post.id }}">{{post.title}}"</a>
                </div>
            </div>
        </article>
    </div>
  {% endfor %}



</section>


{% endblock %}

python_cms/templates/connect_us.html.j2
{% extends 'base.html.j2' %}
{% block title %} Csatlakozz {% endblock %}

{%block headsource %}  
{# <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> #}
<link rel="stylesheet" href="{{ url_for('static', filename='connect_us.css') }}" />
{% endblock %}

{% block contact %}


{% endblock %}

python_cms/templates/connection.html.j2
{% extends 'base.html.j2' %}
{% block title %} Kapcsolat {% endblock %}

{%block headsource %}  
{# <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> #}
<link rel="stylesheet" href="{{ url_for('static', filename='connect.css') }}" />
{% endblock %}


{% block content %}
<h3>Kapcsolat</h3>

<div class="contact">
    <div class="info">
        <h4>Kapcsolati információk</h4>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit facere blanditiis enim officiis impedit molestias facilis, debitis deleniti, beatae porro repellat. Sapiente labore deleniti, inventore architecto iste, praesentium exercitationem voluptatibus earum ea enim, at facere voluptate! Omnis explicabo vel aperiam unde quo. Sunt velit, eum perspiciatis, nostrum sequi nobis obcaecati veritatis a corrupti maxime vitae ipsam, blanditiis ab quod nam cupiditate. Adipisci maiores similique odio consectetur tempore debitis quisquam iure magnam consequuntur, enim quibusdam totam iste? Tempora eveniet eaque quos. Aliquam blanditiis dignissimos accusamus quidem perspiciatis, reiciendis unde eaque itaque atque voluptates quibusdam officia, nesciunt modi tempora numquam consequatur odio!</p>

        <address>
            <ul>
                <li><a href="mailto:info@solamateria.hu"><strong>email</strong>: info@solamateria.hu</a></li>
                <li><strong>telefon</strong>: 0610-123-45-67</li>
                <li><strong>cím</strong>: 1111 Budapest Alap utca 1</li>
            </ul>
        </address>

    </div>

    
    <form action="/connection" method="POST" class="send" enctype="multipart/form-data">
    <h4>Küldj nekünk üzenetet</h4>
        {{ form.csrf_token() }}
        
        <div  class="input">
            <label for="email"><strong>{{ form.email.label }}</strong></label>
            {# <span>Email</span> #}
            <input type="email" name="email" placeholder="Email" required>
        </div>


        <div  class="input">
            <label for="subject"><strong>{{ form.subject.label }}</strong></label>       
            {# <span>Tárgy</strong></span> #}
            <input type="text" name="subject" placeholder="Tárgy" required>
        </div>

        <div  class="input">
            <label for="message"><strong>{{ form.message.label }}</strong></label> 
            {# <span><strong>Üzenet</strong></span> #}
            <textarea name="message" placeholder="Üzenet" required></textarea>
        </div>

        <div class="button">
            {{form.submit(class="submit")}}
        </div>

    </form>
</div>

{% endblock%}

python_cms/templates/filozofia.html.j2
{% extends 'base.html.j2' %}
{% block title %} Filozófia {% endblock %}

{%block headsource %}  
{# <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> #}
<link rel="stylesheet" href="../static/style_index.css"> 
{% endblock %}

{% block content %}
  {% if posts|length == 0 %}
  <h1 class="no-posts">Nincsenek bejegyzések</h1>
  {% endif %}

  {% for message in get_flashed_messages()  %}
   <div class="toast toast-success">
       <button class="btn btn-clear float-right"></button>
         {{message}}
   </div>
  {% endfor %}
      {% if posts %}
    <h3>Filozófia</h3>
    {% endif %}

<section class="posts">

  {% for post in posts|selectattr("category_name", "equalto", "Filozófia") %}
    <div class="post">
        <div class="post-data">
            <div class="img-div">
            <a href="/post/{{ post.id }}">
              <img src="/files/{{post.teaser_image}}" alt="">
            </a>
                
            </div>
            <div class="other-data">
                <div class="catauth">
                    <div class="post-category"><a href="#" >{{ post.category_name }}</a></div>
                    <div class="post-auther"><a href="/author/{{post.author_id}}">{{post.author.name}}</a></div>
                </div>
                <div class="title">
                    <a href="/post/{{ post.id }}">{{post.title}}"</a>
                </div>
            </div>
        </div>
    </div>
  {% endfor %}

</section>


{% endblock %}